routes/web.php
<?php

use App\Http\Controllers\AdressController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\InfoController;
use App\Http\Controllers\NetworkController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HeaderController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\SiteController::class, 'index']);

Route::get('/login', function () {
    return redirect()->route('login');
});

Auth::routes(['register' => false]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Profile Routes
Route::prefix('profile')->name('profile.')->middleware('auth')->group(function(){
    Route::get('/', [HomeController::class, 'getProfile'])->name('detail');
    Route::post('/update', [HomeController::class, 'updateProfile'])->name('update');
    Route::post('/change-password', [HomeController::class, 'changePassword'])->name('change-password');
});

// Header Routes
Route::prefix('header')->name('header.')->middleware('auth')->group(function(){
    Route::get('/', [HeaderController::class, 'index'])->name('index');
    Route::get('/create', [HeaderController::class, 'create'])->name('create');
    Route::post('/store', [HeaderController::class, 'store'])->name('store');
    Route::get('/edit/{header}', [HeaderController::class, 'edit'])->name('edit');
    Route::put('/update/{header}', [HeaderController::class, 'update'])->name('update');

});

// Info Routes
Route::prefix('info')->name('info.')->middleware('auth')->group(function(){
    Route::get('/index', [InfoController::class, 'index'])->name('index');
    Route::get('/create', [InfoController::class, 'create'])->name('create');
    Route::post('/store', [InfoController::class, 'store'])->name('store');
    Route::get('/edit/{info}', [InfoController::class, 'edit'])->name('edit');
    Route::put('/update/{info}', [InfoController::class, 'update'])->name('update');

});

// Network Routes
Route::prefix('network')->name('network.')->middleware('auth')->group(function(){
    Route::get('/index', [NetworkController::class, 'index'])->name('index');
    Route::get('/create', [NetworkController::class, 'create'])->name('create');
    Route::post('/store', [NetworkController::class, 'store'])->name('store');
    Route::get('/edit/{network}', [NetworkController::class, 'edit'])->name('edit');
    Route::put('/update/{network}', [NetworkController::class, 'update'])->name('update');

});

// Adress Routes
Route::prefix('adress')->name('adress.')->middleware('auth')->group(function(){
    Route::get('/index', [AdressController::class, 'index'])->name('index');
    Route::get('/create', [AdressController::class, 'create'])->name('create');
    Route::post('/store', [AdressController::class, 'store'])->name('store');
    Route::get('/edit/{adress}', [AdressController::class, 'edit'])->name('edit');
    Route::put('/update/{adress}', [AdressController::class, 'update'])->name('update');

});



// Roles
Route::resource('roles', App\Http\Controllers\RolesController::class);

// Permissions
Route::resource('permissions', App\Http\Controllers\PermissionsController::class);

// Users
Route::middleware('auth')->prefix('users')->name('users.')->group(function(){
    Route::get('/', [UserController::class, 'index'])->name('index');
    Route::get('/create', [UserController::class, 'create'])->name('create');
    Route::post('/store', [UserController::class, 'store'])->name('store');
    Route::get('/edit/{user}', [UserController::class, 'edit'])->name('edit');
    Route::put('/update/{user}', [UserController::class, 'update'])->name('update');
    Route::delete('/delete/{user}', [UserController::class, 'delete'])->name('destroy');
    Route::get('/update/status/{user_id}/{status}', [UserController::class, 'updateStatus'])->name('status');


    Route::get('/import-users', [UserController::class, 'importUsers'])->name('import');
    Route::post('/upload-users', [UserController::class, 'uploadUsers'])->name('upload');

    Route::get('export/', [UserController::class, 'export'])->name('export');

});

app/Models/Info.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Info extends Model
{
    use HasFactory;

    const STATUS_ACTIVE = 1;
    const STATUS_INACTIVE = 0;

    protected $table = 'info';

    protected $fillable = [
        'title',
        'image',
        'info',
        'created_at',
        'updated_at',
        'status'

    ];


}

app/Http/Controllers/InfoController.php
<?php

namespace App\Http\Controllers;
use App\Models\Info;
use Illuminate\Http\Request;
use Carbon\Carbon;
class InfoController extends Controller
{
    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $info = Info::latest()->paginate(5);

        return view('info.index',compact('info'));
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('info.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required',
            'info' => 'required',
        ]);

        Info::query()->delete();

        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file->move(public_path('public/image'), $filename);
            $data['image']= $filename;
        }

        Info::create([
            'image' => 'public/image/' . $filename,
            'title' => $request->title,
            'info' => $request->info,
            'created_at' => Carbon::now(),
            'updated_at' => Carbon::now(),
        ]);

        return redirect()->route('info.index')
            ->with('success','Info created successfully.');
    }

    public function edit(Info $info)
    {

        return view('info.edit',compact('info'));
    }

    public function update(Request $request, Info $info)
    {
        $request->validate([
            'title' => 'required',
            'info' => 'required',
        ]);

        if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file->move(public_path('public/image'), $filename);
            $data['image']= $filename;
            $filename = 'public/image/' . $filename;
        }

        $info->update([
            'image' => $filename ?? $info->image,
            'title' => $request->title,
            'info' => $request->info,
            'updated_at' => Carbon::now(),
        ]);

        return redirect()->route('info.index')
            ->with('success','Info updated successfully');
    }
}

resources/views/info/create.blade.php
@extends('layouts.app')

@section('title', 'Add Info')

@section('content')


    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Add info</h1>
            <a href="{{route('info.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
        </div>

        {{-- Alert Messages --}}
        @include('common.alert')

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-info py-3">
                <h6 class="m-0 font-weight-bold text-primary">Add New Info</h6>
            </div>
            <form method="POST" action="{{route('info.store')}}" enctype='multipart/form-data'>
                @csrf
                <div class="card-body">
                    <div class="form-group row">

                        {{-- First Name --}}
                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Title</label>
                            <input
                                type="text"
                                class="form-control form-control-user @error('title') is-invalid @enderror"
                                id="exampleTitle"
                                placeholder="Title"
                                name="title"
                                value="{{ old('title') }}">

                            @error('info')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>
                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Info</label>
                            <input
                                type="text"
                                class="form-control form-control-user @error('info') is-invalid @enderror"
                                id="exampleInfo"
                                placeholder="Info"
                                name="info"
                                value="{{ old('info') }}">

                            @error('info')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>

                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Image</label>
                            <input
                                type="file"
                                class="form-control form-control-user @error('image') is-invalid @enderror"
                                id="exampleImage"
                                placeholder="Image"
                                name="image"
                                value="{{ old('image') }}">

                            @error('created_at')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>
                    </div>


                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success btn-user float-right mb-3">Save</button>
                    <a class="btn btn-primary float-right mr-3 mb-3" href="{{ route('info.index') }}">Cancel</a>
                </div>
            </form>
        </div>

    </div>
@endsection

resources/views/info/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Info')

@section('content')

    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Edit Infos</h1>
            <a href="{{route('info.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                    class="fas fa-arrow-left fa-sm text-white-50"></i> Back</a>
        </div>

        {{-- Alert Messages --}}
        @include('common.alert')

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Edit Info</h6>
            </div>
            <form method="POST" action="{{route('info.update', $info)}}" enctype='multipart/form-data'>
                @csrf
                @method('PUT')

                <div class="card-body">
                    <div class="form-group row">

                        {{-- Last Name --}}
                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Title</label>
                            <input
                                type="text"
                                class="form-control form-control-user @error('title') is-invalid @enderror"
                                id="exampleLastName"
                                placeholder="Title"
                                name="title"
                                value="{{ old('title') ? old('title') : $info->title }}">

                            @error('title')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>

                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Image</label>
                            <input
                                type="file"
                                class="form-control form-control-user @error('Image') is-invalid @enderror"
                                id="exampleImage"
                                placeholder=" Image"
                                name="image"
                                value="{{ old('Image') ?  old('Image') : $info->Image}}">

                            @error('Image')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>

                        <div class="col-sm-6 mb-3 mt-3 mb-sm-0">
                            <label><span style="color:red;">*</span>Info</label>
                            <input
                                type="text"
                                class="form-control form-control-user @error('info') is-invalid @enderror"
                                id="exampleInfo"
                                placeholder="Info"
                                name="info"
                                value="{{ old('info') ? old('info') : $info->info }}">

                            @error('info')
                            <span class="text-danger">{{$message}}</span>
                            @enderror
                        </div>

                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success btn-user float-right mb-3">Update</button>
                    <a class="btn btn-primary float-right mr-3 mb-3" href="{{ route('header.index') }}">Cancel</a>
                </div>
            </form>
        </div>

    </div>


@endsection

resources/views/info/index.blade.php
@extends('layouts.app')

@section('title', 'Info List')

@section('content')
    <div class="container-fluid">

        <!-- Page Heading -->
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Info</h1>
            <div class="row">
                <div class="col-md-12">
                    <a href="{{ route('info.create') }}" class="btn btn-sm btn-primary">
                        <i class="fas fa-plus"></i> Add New
                    </a>
                </div>

            </div>

        </div>

        {{-- Alert Messages --}}
        @include('common.alert')

        <!-- DataTales Example -->
        <div class="card shadow mb-4">
            <div class="card-info py-3">
                <h6 class="m-0 font-weight-bold text-primary">All Infos</h6>

            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th width="20%">Title</th>
                            <th width="20%">Info</th>
                            <th width="20%">Image</th>
                            <th width="20%">Created_at</th>
                            <th width="20%">Updated_at</th>
                            <th width="15%">Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($info as $inf)
                            <tr>
                                <td>{{ $inf->title }}</td>
                                <td>{{ $inf->info }}</td>
                                <td><img src="/{{ $inf->image }}" alt="" style="width: 150px"></td>
                                <td>{{ $inf->created_at }}</td>
                                <td>{{ $inf->updated_at }}</td>
                                <td>
                                    <a href="{{ route('info.edit', $inf) }}"
                                       class="btn btn-primary m-2">
                                        <i class="fa fa-pen"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                    {{ $info->links() }}
                </div>
            </div>
        </div>

    </div>


@endsection

@section('scripts')

@endsection

resources/views/info/layout.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>IN BAZAAR </title>
</head>
<body>

<div class="container">
    @yield('content')
</div>

</body>
</html>